/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'color-brands': 'var(--color-brands)',
        'neutral-bg': 'var(--neutral-bg)',
        'neutral-accent': 'var(--neutral-accent)',
        'dark-neutral-bg': 'var(--dark-neutral-bg)',
        'dark-neutral-border': 'var(--dark-neutral-border)',
        gray: {
          0: 'var(--gray-0)',
          100: 'var(--gray-100)',
          200: 'var(--gray-200)',
          300: 'var(--gray-300)',
          400: 'var(--gray-400)',
          500: 'var(--gray-500)',
          600: 'var(--gray-600)',
          700: 'var(--gray-700)',
          800: 'var(--gray-800)',
          900: 'var(--gray-900)',
          1000: 'var(--gray-1000)',
          1100: 'var(--gray-1100)',
        },
        'gray-dark': {
          0: 'var(--dark-gray-0)',
          100: 'var(--dark-gray-100)',
          200: 'var(--dark-gray-200)',
          300: 'var(--dark-gray-300)',
          400: 'var(--dark-gray-400)',
          500: 'var(--dark-gray-500)',
          600: 'var(--dark-gray-600)',
          700: 'var(--dark-gray-700)',
          800: 'var(--dark-gray-800)',
          900: 'var(--dark-gray-900)',
          1000: 'var(--dark-gray-1000)',
          1100: 'var(--dark-gray-1100)',
        },
        blue: 'var(--blue-accent)',
        green: 'var(--green-accent)',
        violet: 'var(--violet-accent)',
        orange: 'var(--orange-accent)',
        yellow: 'var(--yellow-accent)',
        indigo: 'var(--indigo-accent)',
        emerald: 'var(--emerald-accent)',
        fuchsia: 'var(--fuchsia-accent)',
        red: 'var(--red-accent)',
        sky: 'var(--sky-accent)',
        pink: 'var(--pink-accent)',
      },
      fontFamily: {
        sans: ['Noto Sans', 'sans-serif'],
        accent: ['Chivo', 'sans-serif'],
      },
      fontSize: {
        'header-1': ['40px', '60px'],
        'header-2': ['32px', '39px'],
        'header-3': ['28px', '34px'],
        'header-4': ['28px', '34px'],
        'header-5': ['24px', '30px'],
        'header-6': ['20px', '18px'],
        'header-7': ['18px', '22px'],
        subtitle: ['16px', '16px'],
        'subtitle-semibold': ['16px', '20px'],
        'btn-label': ['16px', '16px'],
        'mini-btn-label': ['14px', '12px'],
        normal: ['14px', '16px'],
        desc: ['12px', '16px'],
        'mini-desc': ['9px', '11px'],
      },
      borderRadius: {
        xl: '12px',
        '2xl': '16px',
      },
      boxShadow: {
        dropdown: '0 40px 120px 0 rgba(0, 0, 0, 0.122)',
        search: '0 20px 60px -6px rgba(0, 0, 0, 0.04)',
      },
    },
  },
  plugins: [
    require('tailwind-scrollbar-hide'),
  ],
  corePlugins: {
    preflight: false,
  },
}
